# Generated by Django 5.1.3 on 2025-03-22 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("album_name", models.CharField(max_length=200)),
                ("artist_name", models.CharField(max_length=200)),
                ("optional_writing", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ep_name", models.CharField(max_length=200)),
                ("artist_name", models.CharField(max_length=200)),
                ("optional_writing", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist_name", models.CharField(max_length=200)),
                ("optional_writing", models.TextField(blank=True, null=True)),
                ("albums", models.ManyToManyField(blank=True, to="music_rating.album")),
                ("eps", models.ManyToManyField(blank=True, to="music_rating.ep")),
                (
                    "artist_rating",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="music_rating.rating",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RateSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artists", models.ManyToManyField(to="music_rating.artist")),
            ],
        ),
        migrations.AddField(
            model_name="ep",
            name="ep_rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="music_rating.rating",
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="album_rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="music_rating.rating",
            ),
        ),
        migrations.CreateModel(
            name="Single",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("single_name", models.CharField(max_length=200)),
                ("artist_name", models.CharField(max_length=200)),
                ("optional_writing", models.TextField(blank=True, null=True)),
                (
                    "single_rating",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="music_rating.rating",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="artist",
            name="singles",
            field=models.ManyToManyField(blank=True, to="music_rating.single"),
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_name", models.CharField(max_length=200)),
                ("no_of_streams", models.IntegerField(null=True)),
                ("no_of_minutes", models.IntegerField(null=True)),
                ("optional_writing", models.TextField(blank=True, null=True)),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="songs_album",
                        to="music_rating.album",
                    ),
                ),
                (
                    "ep",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="songs_ep",
                        to="music_rating.ep",
                    ),
                ),
                (
                    "feat_artists",
                    models.ManyToManyField(
                        blank=True,
                        related_name="featured_songs",
                        to="music_rating.artist",
                    ),
                ),
                (
                    "rating",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="music_rating.rating",
                    ),
                ),
                (
                    "single",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="songs_single",
                        to="music_rating.single",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="single",
            name="songs",
            field=models.ManyToManyField(
                related_name="single_songs", to="music_rating.song"
            ),
        ),
        migrations.AddField(
            model_name="ep",
            name="songs",
            field=models.ManyToManyField(
                related_name="ep_songs", to="music_rating.song"
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="songs",
            field=models.ManyToManyField(
                related_name="album_songs", to="music_rating.song"
            ),
        ),
    ]
