# Generated by Django 5.1.3 on 2024-12-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music_rating", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artist",
            old_name="name",
            new_name="artist_name",
        ),
    ]
