# Generated by Django 5.1.3 on 2025-03-22 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music_rating", "0001_initial"),
    ]

    operations = []
