# Generated by Django 5.1.3 on 2025-03-23 00:32

from django.db import migrations, models

def create_default_rate_system(apps, schema_editor):
    # Get the RateSystem model using apps.get_model
    RateSystem = apps.get_model('music_rating', 'RateSystem')
    
    # Create a default RateSystem if it doesn't exist
    RateSystem.objects.get_or_create(name='OG')

class Migration(migrations.Migration):

    dependencies = [
        ("music_rating", "0002_auto_20250322_0109"),
    ]

    operations = [
        migrations.AddField(
            model_name='ratesystem',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='ratesystem',
            name='description',  # Replace with your actual field name
            field=models.TextField(null=True, blank=True),  # Adjust as needed
        ),

        migrations.RunPython(create_default_rate_system),
    ]
