# Generated by Django 5.1.3 on 2025-03-01 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_rating", "0002_add_feat_artists_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="album_rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="music_rating.rating",
            ),
        ),
    ]
