# Generated by Django 5.1.3 on 2025-03-23 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_rating", "0003_auto_20250323_0032"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ratesystem",
            name="artists",
        ),
        migrations.AddField(
            model_name="artist",
            name="rate_system",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="music_rating.ratesystem",
            ),
        ),
        migrations.AlterField(
            model_name="ratesystem",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="ratesystem",
            name="name",
            field=models.CharField(default="OG", max_length=255),
        ),
    ]
