# Generated by Django 5.1.3 on 2025-03-21 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_rating", "0003_alter_album_album_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="artist_rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="music_rating.rating",
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="album_rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="music_rating.rating",
            ),
        ),
        migrations.AlterField(
            model_name="ep",
            name="ep_rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="music_rating.rating",
            ),
        ),
        migrations.AlterField(
            model_name="single",
            name="single_rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="music_rating.rating",
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="songs_album",
                to="music_rating.album",
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="ep",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="songs_ep",
                to="music_rating.ep",
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="music_rating.rating",
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="single",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="songs_single",
                to="music_rating.single",
            ),
        ),
    ]
